[package]
name = "handshake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etherparse = "0.13.0"
nix = "0.26.2"
rand = "0.8.5"
thiserror = "1.0.40"
tidy-tuntap = "0.3.1"
